### save
POST http://localhost:8282/saveCategory
Content-Type: application/json

{
  "id": 2,
  "name": "categoryDto3"
}

### findAll
GET http://localhost:8282/allCategory
Accept: application/json

### findAllById

GET http://localhost:8282/findAllCategoryByIds?ids=6,8
Content-Type: application/json

### findById

GET http://localhost:8282/findCategoryById?id=7
Accept: application/json

### delete

GET http://localhost:8282/deleteCategory?id=7
Accept: application/json
