### save
POST http://localhost:8282/saveGroup
Content-Type: application/json

{
  "id": 4,
  "name": "group1",
  "users": [
    {
      "id": 1,
      "name": "Jakub",
      "surname": "Glinka",
      "email": "jakub@mail.com",
      "password": "haslo"
    }
  ],
  "journals": [
    {
      "id": 3,
      "title1": "tyt1",
      "issn1": "i1",
      "eissn1": "e1",
      "title2": "tyt2",
      "issn2":  "i2",
      "eissn2": "e2",
      "points": 50,
      "categories": [
        {
          "id": 2,
          "name": "category1"
        }
      ]
    }
  ]
}

### findAll
GET http://localhost:8282/allGroup
Accept: application/json

### findById

GET http://localhost:8282/findGroupById?id=4
Accept: application/json

### addJournal

GET http://localhost:8282/addJournalToGroup?groupId=4&journalId=3
Accept: application/json

### addUser

GET http://localhost:8282/addUserToGroup?groupId=4&userId=1
Accept: application/json

### removeJoural

GET http://localhost:8282/removeJournalFromGroup?groupId=4&journalId=3
Accept: application/json

###removeUser

GET http://localhost:8282/removeUserFromGroup?groupId=4&userId=1
Accept: application/json
